name: Kotlin
description: "Prerequisite Plugin to load Kotlin-based Plugin with Spigot"
author: JetBrains
authors:
  - Srain3
website: "https://github.com/Srain3/Kotlin"
main: com.github.srain3.Kotlin
load: STARTUP
version: "2.3.0"
api-version: "1.21"